server:
  port: 8090
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  config:
    activate:
      on-profile: stage
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ktds
    username: goyang
    password: "goyang00!"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
  data:
    redis:
      host: 192.168.0.252
      port: 6379
      timeout: 1000

jwt:
  access-token:
    secret: +iBcUJRWGvl+94+ow4nXV1fzWIq4rph8x7MyRmrtWio=
    expiration: 3600000
  refresh-token:
    secret: gtzRlqF6bIkmOi5i15A9G5xbLdwiAMmZi6JPOeemC1E=
    expiration: 86400000

logging:
  level:
    org: INFO
    com: DEBUG
    root: INFO