server:
  port: 8085
  servlet:
    encoding:
      charset: UTF-8
      enabled: true

spring:
  config:
    activate:
      on-profile: local
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:mariadb://localhost:3306/ktds?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234

    secondary:
#      url: jdbc:sqlserver://10.107.10.30:1433;databaseName=Parking
      url: "jdbc:sqlserver://192.168.4.95:1433;databaseName=Parking;encrypt=true;trustServerCertificate=true"
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      username: Digital_tw
      password: Digital_tw
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDBDialect
#    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
rabbitmq:
  host: 192.168.4.36
  port: 5672
  username: pluxity
  password: pluxity123
  queue:
    alarm-was1: alarm.queue.was1
    alarm-was2: alarm.queue.was2
    notice-was1: notice.queue.was1
    notice-was2: notice.queue.was2
    alarm-disable-was1: alarm.disable.queue.was1
    alarm-disable-was2: alarm.disable.queue.was2
  exchange:
    alarm: alarm.exchange
    notice: notice.exchange
    alarm-disable: alarm.disable.exchange

event:
  server:
    access-key: SCADA
    base-url: http://1094.iptime.org

logging:
  level:
    com: DEBUG
    root: INFO
    org:
      hibernate:
        SQL: DEBUG

root-path:
  upload: C:/Dev/Upload
  files: C:/Dev/files

cctv:
  ws-relay-url: ws://127.0.0.1
  ws-relay-port: 4001
  http-relay-url: http://127.0.0.1
  http-relay-port: 4002
  LG-server-ip: 10.20.11.231
  LG-server-Port: 9100
  LG-live-port: 555
  LG-playback-port: 554
  username: admin
  password: pluxity123!@#

tag:
  client:
    max-retries: 3
