server:
  port: 8085
  servlet:
    encoding:
      charset: UTF-8
      enabled: true

spring:
  config:
    activate:
      on-profile: local
  devtools:
    livereload:
      enabled: true
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:mariadb://localhost:3306/test?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MariaDBDialect
#    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 1000
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
  queue:
    alarm-was1: alarm.queue.was1
    alarm-was2: alarm.queue.was2
    notice-was1: notice.queue.was1
    notice-was2: notice.queue.was2
    alarm-disable-was1: alarm.disable.queue.was1
    alarm-disable-was2: alarm.disable.queue.was2
  exchange:
    alarm: alarm.exchange
    notice: notice.exchange
    alarm-disable: alarm.disable.exchange

logging:
  level:
    com: DEBUG
    root: INFO
    org:
      hibernate:
        SQL: DEBUG

root-path:
  upload: C:/Dev/Upload