server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true

spring:
  config:
    activate:
      on-profile: local
  devtools:
    livereload:
      enabled: true
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/ktds;
    driver-class-name: org.h2.Driver
    username: pluxity
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true

jwt:
  access-token:
    secret-key: +iBcUJRWGvl+94+ow4nXV1fzWIq4rph8x7MyRmrtWio=
    expiration: 3600000
  refresh-token:
    secret-key: gtzRlqF6bIkmOi5i15A9G5xbLdwiAMmZi6JPOeemC1E=
    expiration: 86400000

logging:
  level:
    org: INFO
    com: DEBUG
    root: INFO

root-path:
  upload: C:/Dev/Upload